#pragma once

// Pin remapping (damaged due to ESD)
#undef MATRIX_ROW_PINS_RIGHT
#define MATRIX_ROW_PINS_RIGHT {B1, B3, F5, B6}

// RGB Lighting (https://docs.qmk.fm/features/rgblight)
#define RGBLIGHT_SPLIT

// RGB Matrix (https://docs.qmk.fm/features/rgb_matrix)
#define ENABLE_RGB_MATRIX_HUE_BREATHING_DUAL
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#define ENABLE_RGB_MATRIX_MULTISPLASH
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#define RGB_MATRIX_DEFAULT_HUE 208
#define RGB_MATRIX_HUE_BREATHING_DUAL_SLAVE_HUE_DISTANCE 190
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CUSTOM_HUE_BREATHING_DUAL
